# Generated by Django 5.2.16 on 2026-07-30 10:39

import apps.orders.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=apps.orders.models.generate_order_number, editable=False, max_length=32, unique=True, verbose_name='Номер')),
                ('access_token', models.CharField(default=apps.orders.models.generate_access_token, editable=False, max_length=64, unique=True, verbose_name='Токен доступу')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('awaiting_payment', 'Очікує оплати'), ('paid', 'Оплачено'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], db_index=True, default='new', max_length=32, verbose_name='Статус')),
                ('customer_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('customer_phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('delivery_type', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('courier', 'Курʼєр')], max_length=32, verbose_name='Доставка')),
                ('np_city_ref', models.CharField(blank=True, max_length=64)),
                ('np_city_name', models.CharField(blank=True, max_length=255)),
                ('np_warehouse_ref', models.CharField(blank=True, max_length=64)),
                ('np_warehouse_name', models.CharField(blank=True, max_length=255)),
                ('np_point_type', models.CharField(blank=True, choices=[('warehouse', 'Відділення'), ('locker', 'Поштомат')], max_length=32)),
                ('courier_city', models.CharField(blank=True, max_length=120)),
                ('courier_street', models.CharField(blank=True, max_length=255)),
                ('courier_building', models.CharField(blank=True, max_length=64)),
                ('courier_apartment', models.CharField(blank=True, max_length=64)),
                ('courier_comment', models.TextField(blank=True)),
                ('payment_type', models.CharField(choices=[('liqpay', 'LiqPay'), ('cash_on_delivery', 'Оплата при отриманні')], max_length=32, verbose_name='Оплата')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('sku', models.CharField(max_length=64, verbose_name='Артикул')),
                ('variant_label', models.CharField(blank=True, max_length=120, verbose_name='Модифікація')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
    ]
