# Generated by Django 5.2.16 on 2026-08-24 14:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_labelicon_title_uk_ru'),
        ('orders', '0002_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier_apartment',
            field=models.CharField(blank=True, max_length=64, verbose_name='Курʼєр: квартира'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_building',
            field=models.CharField(blank=True, max_length=64, verbose_name='Курʼєр: будинок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Курʼєр: місто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_comment',
            field=models.TextField(blank=True, verbose_name='Курʼєр: коментар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Курʼєр: вулиця'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='np_city_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='НП: місто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='np_city_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='НП: код міста'),
        ),
        migrations.AlterField(
            model_name='order',
            name='np_point_type',
            field=models.CharField(blank=True, choices=[('warehouse', 'Відділення'), ('locker', 'Поштомат')], max_length=32, verbose_name='НП: тип пункту'),
        ),
        migrations.AlterField(
            model_name='order',
            name='np_warehouse_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='НП: відділення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='НП: код відділення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Підсумок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Разом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant', verbose_name='Варіант'),
        ),
    ]
