# Generated by Django 5.2.16 on 2026-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_type_monopay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False, help_text='Службове: після скасування залишок уже нараховано назад.', verbose_name='Залишок повернуто'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_reserved',
            field=models.BooleanField(default=False, help_text='Службове: при створенні замовлення qty списано зі складу.', verbose_name='Залишок зарезервовано'),
        ),
    ]
