# Generated by Django 5.2.16 on 2026-07-30 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ПІБ')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('default_city', models.CharField(blank=True, max_length=120, verbose_name='Місто')),
                ('default_street', models.CharField(blank=True, max_length=255, verbose_name='Вулиця')),
                ('default_building', models.CharField(blank=True, max_length=64, verbose_name='Будинок')),
                ('default_apartment', models.CharField(blank=True, max_length=64, verbose_name='Квартира')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Профілі',
            },
        ),
    ]
