[project]
name = "ogemed"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "Django==5.2.16",
    "django-environ==0.12.0",
    "django-htmx==1.27.0",
    "django-q2==1.10.0",
    "Pillow==12.1.0",
    "whitenoise==6.11.0",
]

[tool.uv]
package = false

[tool.vercel]
entrypoint = "config.wsgi:application"

[tool.vercel.scripts]
build = "python -u build.py"
