# Generated by Django 5.2.16 on 2026-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('manager_email', models.EmailField(blank=True, max_length=254, verbose_name='Email менеджера')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('viber_url', models.URLField(blank=True, verbose_name='Viber')),
                ('telegram_consultant_url', models.URLField(blank=True, help_text='Deep-link на чат консультанта', verbose_name='Telegram консультант (FAB)')),
                ('brand_tagline_uk', models.CharField(blank=True, default='Косметика з турботою про вас', max_length=255, verbose_name='Слоган (UK)')),
                ('brand_tagline_ru', models.CharField(blank=True, default='Косметика с заботой о вас', max_length=255, verbose_name='Слоган (RU)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
