# Generated by Django 5.2.16 on 2026-07-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG/SVG з прозорим фоном. Порожньо = логотип із static/img/logo.png', upload_to='site/', verbose_name='Логотип'),
        ),
    ]
