# Generated by Django 5.2.16 on 2026-08-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса (UK)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Посилання для iframe, напр. OpenStreetMap embed', verbose_name='URL карти (iframe)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Години роботи (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Години роботи (UK)'),
        ),
    ]
