# Generated by Django 5.2.16 on 2026-08-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_fop_requisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFiltersSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Каталог — Фільтри',
                'verbose_name_plural': 'Каталог — Фільтри',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='CatalogSeoSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Каталог — SEO',
                'verbose_name_plural': 'Каталог — SEO',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactsIntroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Контакти — Intro',
                'verbose_name_plural': 'Контакти — Intro',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeBenefitsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Переваги',
                'verbose_name_plural': 'Головна — Переваги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeBrandsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Бренди',
                'verbose_name_plural': 'Головна — Бренди',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeCareSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Підбір догляду',
                'verbose_name_plural': 'Головна — Підбір догляду',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeCategoriesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Категорії',
                'verbose_name_plural': 'Головна — Категорії',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeProductsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Товари',
                'verbose_name_plural': 'Головна — Товари',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomePromoSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Промо',
                'verbose_name_plural': 'Головна — Промо',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ShippingMethodsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Доставка — Методи',
                'verbose_name_plural': 'Доставка — Методи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ShippingPaymentSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Доставка — Оплата',
                'verbose_name_plural': 'Доставка — Оплата',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Підвал сайту',
                'verbose_name_plural': 'Підвал сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteHeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Шапка сайту',
                'verbose_name_plural': 'Шапка сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота'),
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('catalog', 'Каталог'), ('about', 'Про нас'), ('shipping', 'Доставка'), ('contacts', 'Контакти'), ('site', 'Сайт')], max_length=32, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ блоку')),
                ('label', models.CharField(max_length=128, verbose_name='Назва в адмінці')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('url', 'URL')], default='text', max_length=16, verbose_name='Тип контенту')),
                ('text_html', models.TextField(blank=True, verbose_name='Текст')),
                ('text_html_uk', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_html_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='blocks/', verbose_name='Зображення')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
        ),
    ]
