# Generated by Django 5.2.16 on 2026-08-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_catalogfilterssettings_catalogseosettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Вставте коротке посилання Google Maps (maps.app.goo.gl/…) або повний HTML iframe — сайт сам зробить embed.', verbose_name='Карта Google'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True, verbose_name='Широта (застаріле)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=9, null=True, verbose_name='Довгота (застаріле)'),
        ),
    ]
