# Generated by Django 5.2.16 on 2026-08-24 12:37

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_label_icon_and_map_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteblock',
            name='image',
            field=apps.core.fields.OptimizedImageField(blank=True, max_side=2560, upload_to='blocks/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=apps.core.fields.OptimizedImageField(allow_svg=True, blank=True, help_text='PNG/SVG з прозорим фоном. Порожньо = логотип із static/img/logo.png', max_side=1024, upload_to='site/', verbose_name='Логотип'),
        ),
    ]
