# Generated by Django 5.2.16 on 2026-08-24 13:55

from django.db import migrations


def delete_orphan_site_blocks(apps, schema_editor):
    SiteBlock = apps.get_model("core", "SiteBlock")
    SiteBlock.objects.filter(page__in=["catalog", "shipping"]).delete()
    SiteBlock.objects.filter(page="home", key__startswith="benefit").delete()
    SiteBlock.objects.filter(page="home", key__startswith="categories").delete()
    SiteBlock.objects.filter(page="home", key__startswith="promo").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_optimized_image_field"),
    ]

    operations = [
        migrations.RunPython(delete_orphan_site_blocks, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="CatalogFiltersSettings",
        ),
        migrations.DeleteModel(
            name="CatalogSeoSettings",
        ),
        migrations.DeleteModel(
            name="HomeBenefitsSettings",
        ),
        migrations.DeleteModel(
            name="HomeCategoriesSettings",
        ),
        migrations.DeleteModel(
            name="HomePromoSettings",
        ),
        migrations.DeleteModel(
            name="ShippingMethodsSettings",
        ),
        migrations.DeleteModel(
            name="ShippingPaymentSettings",
        ),
    ]
