# Generated by Django 5.2.16 on 2026-08-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cleanup_dead_cms_and_info_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeherosettings',
            options={'verbose_name': 'Головна — банер', 'verbose_name_plural': 'Головна — банер'},
        ),
    ]
