# Generated by Django 5.2.16 on 2026-08-28 08:39

from django.db import migrations, models


def set_site_phones(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(pk=1).update(
        phone="+380664247233",
        phone_2="+380973086063",
    )


def unset_site_phones(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(pk=1).update(phone_2="")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_products_new_hits_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="phone_2",
            field=models.CharField(blank=True, max_length=32, verbose_name="Телефон 2"),
        ),
        migrations.RunPython(set_site_phones, unset_site_phones),
    ]
