# Generated by Django 5.2.16 on 2026-09-29 07:59

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_tiktok_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=apps.core.fields.OptimizedImageField(allow_svg=True, blank=True, help_text='PNG або SVG з прозорим фоном, читабельний у маленькому розмірі. Вага до 2 МБ. Порожньо = логотип із static/img/logo.png', max_side=1024, upload_to='site/', verbose_name='Логотип'),
        ),
    ]
