# Generated by Django 5.2.16 on 2026-07-30 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='liqpay', max_length=32)),
                ('provider_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payment_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('created', 'Створено'), ('success', 'Успіх'), ('failure', 'Помилка'), ('sandbox', 'Sandbox')], default='created', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Спроба оплати',
                'verbose_name_plural': 'Спроби оплати',
                'ordering': ['-created_at'],
            },
        ),
    ]
