# Generated by Django 5.2.16 on 2026-07-30 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('name_uk', models.CharField(max_length=120, verbose_name='Назва (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=120, verbose_name='Назва (RU)')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='У фільтрах')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибути',
                'ordering': ['sort_order', 'name_uk'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('name_uk', models.CharField(max_length=255, verbose_name='Назва (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Назва (RU)')),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['sort_order', 'name_uk'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('name_uk', models.CharField(max_length=120, verbose_name='Значення (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=120, verbose_name='Значення (RU)')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='Колір HEX')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значення атрибута',
                'verbose_name_plural': 'Значення атрибутів',
                'ordering': ['sort_order', 'name_uk'],
                'unique_together': {('attribute', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('name_uk', models.CharField(max_length=255, verbose_name='Назва (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Назва (RU)')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['sort_order', 'name_uk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('name_uk', models.CharField(max_length=255, verbose_name='Назва (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Назва (RU)')),
                ('short_description_uk', models.TextField(blank=True, verbose_name='Короткий опис (UK)')),
                ('short_description_ru', models.TextField(blank=True, verbose_name='Короткий опис (RU)')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (UK)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Опис (RU)')),
                ('availability', models.CharField(choices=[('in_stock', 'В наявності'), ('on_order', 'Під замовлення'), ('out_of_stock', 'Немає в наявності')], default='in_stock', max_length=20, verbose_name='Наявність')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хіт')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Акція')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('popularity', models.PositiveIntegerField(default=0, verbose_name='Популярність')),
                ('search_text', models.TextField(blank=True, editable=False, verbose_name='Пошуковий індекс')),
                ('attribute_values', models.ManyToManyField(blank=True, related_name='products', to='catalog.attributevalue', verbose_name='Характеристики')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='Бренд')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.category', verbose_name='Категорії')),
                ('primary_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='catalog.category', verbose_name='Основна категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('label_uk', models.CharField(blank=True, max_length=120, verbose_name='Модифікація (UK)')),
                ('label_ru', models.CharField(blank=True, max_length=120, verbose_name='Модифікація (RU)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Залишок')),
                ('availability', models.CharField(blank=True, choices=[('in_stock', 'В наявності'), ('on_order', 'Під замовлення'), ('out_of_stock', 'Немає в наявності')], help_text='Порожньо = успадкувати від товару', max_length=20, verbose_name='Наявність (override)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('attribute_values', models.ManyToManyField(blank=True, related_name='variants', to='catalog.attributevalue', verbose_name='Атрибути варіанту')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Варіант',
                'verbose_name_plural': 'Варіанти',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('alt_uk', models.CharField(blank=True, max_length=255, verbose_name='Alt (UK)')),
                ('alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Alt (RU)')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.productvariant', verbose_name='Варіант')),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Зображення товарів',
                'ordering': ['-is_main', 'sort_order', 'id'],
            },
        ),
    ]
