# Generated by Django 6.0.1 on 2026-07-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='brands/covers/', verbose_name='Зображення для вітрини'),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показувати на головній'),
        ),
        migrations.AddField(
            model_name='brand',
            name='tagline_ru',
            field=models.TextField(blank=True, verbose_name='Короткий опис (RU)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='tagline_uk',
            field=models.TextField(blank=True, verbose_name='Короткий опис (UK)'),
        ),
    ]
