# Generated by Django 5.2.16 on 2026-07-31 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_cover_image_brand_is_featured_brand_tagline_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('group_title_uk', models.CharField(blank=True, help_text="Напр. «Після 1 застосування». Однакові заголовки об'єднуються", max_length=120, verbose_name='Заголовок групи (UK)')),
                ('group_title_ru', models.CharField(blank=True, max_length=120, verbose_name='Заголовок групи (RU)')),
                ('text_uk', models.CharField(max_length=255, verbose_name='Текст (UK)')),
                ('text_ru', models.CharField(blank=True, max_length=255, verbose_name='Текст (RU)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Результат застосування',
                'verbose_name_plural': 'Результати застосування',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('icon', models.CharField(choices=[('drop', 'Крапля (зволоження)'), ('drop_off', 'Крапля перекреслена (без ароматизаторів)'), ('leaf', 'Листок (веган / натуральність)'), ('shield', 'Щит із галочкою (протестовано)'), ('flask_off', 'Колба перекреслена (без парабенів)'), ('sparkle', 'Сяйво (делікатна формула)'), ('heart', 'Серце (без тестів на тваринах)'), ('helix', 'Спіраль (біоформула)')], default='leaf', max_length=20, verbose_name='Іконка')),
                ('icon_image', models.ImageField(blank=True, help_text="Необов'язково. SVG/PNG замість вбудованої іконки", upload_to='products/features/', verbose_name='Власна іконка')),
                ('name_uk', models.CharField(max_length=60, verbose_name='Підпис (UK)')),
                ('name_ru', models.CharField(blank=True, max_length=60, verbose_name='Підпис (RU)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Перевага товару',
                'verbose_name_plural': 'Переваги товару',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
