# Generated by Django 5.2.16 on 2026-07-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productclaim_productfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label_cruelty_free',
            field=models.BooleanField(default=False, verbose_name='Без тестів на тваринах'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_derma_tested',
            field=models.BooleanField(default=False, verbose_name='Дерматологічно протестовано'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_fragrance_free',
            field=models.BooleanField(default=False, verbose_name='Без ароматизаторів'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_gentle',
            field=models.BooleanField(default=False, verbose_name='Делікатна формула'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_hydration',
            field=models.BooleanField(default=False, verbose_name='Глибоке зволоження'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_hypoallergenic',
            field=models.BooleanField(default=False, verbose_name='Гіпоалергенно'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_paraben_free',
            field=models.BooleanField(default=False, verbose_name='Без парабенів'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_vegan',
            field=models.BooleanField(default=False, verbose_name='Веган-формула'),
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
    ]
