# Generated by Django 5.2.16 on 2026-07-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_label_cruelty_free_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductClaim',
        ),
    ]
