# Generated by Django 5.2.16 on 2026-07-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_label_hydration_to_cleansing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Від 1600px по довгій стороні — фото збільшується на сторінці товару.', upload_to='products/', verbose_name='Зображення'),
        ),
    ]
