# Generated by Django 5.2.16 on 2026-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='showcase_image',
            field=models.ImageField(blank=True, help_text='PNG без фону. Якщо порожнє — візьметься фото для каталогу.', upload_to='brands/showcase/', verbose_name='Зображення для вітрини на головній'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Плитка бренду у фільтрах каталогу.', upload_to='brands/covers/', verbose_name='Фото для каталогу'),
        ),
    ]
