# Generated by Django 5.2.16 on 2026-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_brand_showcase_image_alter_brand_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено — категорія зʼявиться в блоці на головній.', verbose_name='Швидкі категорії на головній'),
        ),
    ]
