# Generated by Django 5.2.16 on 2026-08-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_brand_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='У яких категоріях показувати цей атрибут у фільтрах.', related_name='filter_attributes', to='catalog.category', verbose_name='Категорії (фільтри)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Опис / історія (RU)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='Опис / історія (UK)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Варіант для темного фону.', upload_to='brands/', verbose_name='Логотип (темний)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Сайт бренду'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Опис (RU)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='Опис (UK)'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_from', to='catalog.product', verbose_name='Схожі товари'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('draft', 'Чернетка'), ('archived', 'Архів')], default='active', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, verbose_name='Штрихкод'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оптова ціна'),
        ),
    ]
