# Generated by Django 5.2.16 on 2026-08-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_attribute_categories_brand_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='Ключ іконки')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('image', models.ImageField(blank=True, help_text='PNG з прозорим фоном. Порожньо = дефолт із static/img/labels/', upload_to='label_icons/', verbose_name='Зображення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Іконка мітки',
                'verbose_name_plural': 'Іконки міток',
                'ordering': ['title'],
            },
        ),
    ]
