# Generated by Django 5.2.16 on 2026-08-24 12:37

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_label_icon_and_map_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cover_image',
            field=apps.core.fields.OptimizedImageField(blank=True, help_text='Плитка бренду у фільтрах каталогу.', upload_to='brands/covers/', verbose_name='Фото для каталогу'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=apps.core.fields.OptimizedImageField(allow_svg=True, blank=True, max_side=1024, upload_to='brands/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_dark',
            field=apps.core.fields.OptimizedImageField(allow_svg=True, blank=True, help_text='Варіант для темного фону.', max_side=1024, upload_to='brands/', verbose_name='Логотип (темний)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='showcase_image',
            field=apps.core.fields.OptimizedImageField(blank=True, help_text='PNG без фону. Якщо порожнє — візьметься фото для каталогу.', upload_to='brands/showcase/', verbose_name='Зображення для вітрини на головній'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=apps.core.fields.OptimizedImageField(blank=True, upload_to='categories/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='labelicon',
            name='image',
            field=apps.core.fields.OptimizedImageField(allow_svg=True, blank=True, help_text='PNG з прозорим фоном. Порожньо = дефолт із static/img/labels/', max_side=1024, upload_to='label_icons/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=apps.core.fields.OptimizedImageField(help_text='Від 1600px по довгій стороні — фото збільшується на сторінці товару.', upload_to='products/', verbose_name='Зображення'),
        ),
    ]
