# Generated by Django 5.2.16 on 2026-08-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_labelicon_title_uk_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='show_on_home',
        ),
    ]
