# Generated by Django 5.2.16 on 2026-08-25 11:01

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_category_show_on_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=apps.core.fields.OptimizedImageField(help_text='Рекомендовано від 1600px по довгій стороні — інакше збільшення на сторінці товару може бути розмитим. Менше фото все одно можна зберегти.', upload_to='products/', verbose_name='Зображення'),
        ),
    ]
