# Generated by Django 5.2.16 on 2026-09-29 07:18

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_productimage_size_help_soft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=apps.core.fields.OptimizedImageField(blank=True, help_text='Необовʼязково. Рекомендовано від 1600px по довгій стороні — інакше збільшення на сторінці товару може бути розмитим. Менше фото все одно можна зберегти.', upload_to='products/', verbose_name='Зображення'),
        ),
    ]
