# Generated by Django 5.2.16 on 2026-09-29 07:59

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_productimage_image_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='cover_image',
            field=apps.core.fields.OptimizedImageField(blank=True, help_text='Плитка бренду у фільтрах каталогу. ≈1200×1600 (3∶4). Формат: JPG, PNG або WebP. Вага до 20 МБ (краще до 3 МБ).', upload_to='brands/covers/', verbose_name='Фото для каталогу'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='showcase_image',
            field=apps.core.fields.OptimizedImageField(blank=True, help_text='Краще PNG з прозорим фоном, довша сторона ≥1200 px. Якщо порожнє — візьметься фото для каталогу. Вага до 20 МБ (краще до 3 МБ).', upload_to='brands/showcase/', verbose_name='Зображення для вітрини на головній'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=apps.core.fields.OptimizedImageField(blank=True, help_text='Обкладинка ≈1200×1600 (3∶4) або квадрат від 1200 px. Формат: JPG, PNG або WebP. Вага до 20 МБ (краще до 3 МБ).', upload_to='categories/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='labelicon',
            name='image',
            field=apps.core.fields.OptimizedImageField(allow_svg=True, blank=True, help_text='PNG з прозорим фоном, квадрат ≈128–256 px. Вага до 1 МБ. Порожньо = дефолт із static/img/labels/', max_side=1024, upload_to='label_icons/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=apps.core.fields.OptimizedImageField(blank=True, help_text='Необовʼязково. Картка/галерея: ≥1600 px по довгій стороні, пропорції ≈3∶4. Формат: JPG, PNG або WebP. Вага до 20 МБ (краще до 3 МБ). Менше фото все одно можна зберегти.', upload_to='products/', verbose_name='Зображення'),
        ),
    ]
