# Generated by Django 5.2.16 on 2026-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('page_key', models.CharField(blank=True, help_text='about, shipping, returns, contacts, privacy, offer', max_length=64, verbose_name='Ключ сторінки')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Заголовок (UK)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (RU)')),
                ('body_uk', models.TextField(blank=True, verbose_name='Текст (UK)')),
                ('body_ru', models.TextField(blank=True, verbose_name='Текст (RU)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CMS-сторінка',
                'verbose_name_plural': 'CMS-сторінки',
                'ordering': ['sort_order', 'title_uk'],
            },
        ),
    ]
