# Generated by Django 5.2.16 on 2026-07-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Заголовок (UK)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (RU)')),
                ('subtitle_uk', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок (UK)')),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок (RU)')),
                ('cta_label_uk', models.CharField(blank=True, default='Дивитись', max_length=80, verbose_name='CTA (UK)')),
                ('cta_label_ru', models.CharField(blank=True, default='Смотреть', max_length=80, verbose_name='CTA (RU)')),
                ('cta_url', models.CharField(blank=True, default='/katalog/', max_length=255, verbose_name='CTA URL')),
                ('image', models.ImageField(blank=True, upload_to='hero/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Hero-слайд',
                'verbose_name_plural': 'Hero-слайди',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
