# Generated by Django 5.2.16 on 2026-07-30 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_heroslide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('callback', 'Передзвоніть мені'), ('feedback', 'Зворотний звʼязок')], default='callback', max_length=32)),
                ('name', models.CharField(max_length=120, verbose_name='Імʼя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('honeypot', models.CharField(blank=True, editable=False, max_length=120)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лід',
                'verbose_name_plural': 'Ліди',
                'ordering': ['-created_at'],
            },
        ),
    ]
