# Generated by Django 5.2.16 on 2026-08-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_visible', models.BooleanField(default=True, verbose_name='Hero видимий')),
                ('hero_kicker_uk', models.CharField(blank=True, default='OGEMED for you', max_length=80, verbose_name='Hero kicker (UK)')),
                ('hero_kicker_ru', models.CharField(blank=True, default='OGEMED for you', max_length=80, verbose_name='Hero kicker (RU)')),
                ('hero_title_uk', models.CharField(blank=True, default='Краса з турботою про вас', max_length=160, verbose_name='Hero заголовок (UK)')),
                ('hero_title_ru', models.CharField(blank=True, default='Красота с заботой о вас', max_length=160, verbose_name='Hero заголовок (RU)')),
                ('hero_text_uk', models.TextField(blank=True, default='Ми допомагаємо обрати догляд, якому можна довіряти — спокійно, чесно і з увагою до вашої шкіри.', verbose_name='Hero текст (UK)')),
                ('hero_text_ru', models.TextField(blank=True, default='Мы помогаем выбрать уход, которому можно доверять — спокойно, честно и с вниманием к вашей коже.', verbose_name='Hero текст (RU)')),
                ('hero_image', models.ImageField(blank=True, upload_to='about/', verbose_name='Hero зображення')),
                ('history_visible', models.BooleanField(default=True, verbose_name='Історія видима')),
                ('history_kicker_uk', models.CharField(blank=True, default='Історія', max_length=80, verbose_name='Історія kicker (UK)')),
                ('history_kicker_ru', models.CharField(blank=True, default='История', max_length=80, verbose_name='Історія kicker (RU)')),
                ('history_title_uk', models.CharField(blank=True, default='Як зʼявився OGEMED for you', max_length=160, verbose_name='Історія заголовок (UK)')),
                ('history_title_ru', models.CharField(blank=True, default='Как появился OGEMED for you', max_length=160, verbose_name='Історія заголовок (RU)')),
                ('history_body_uk', models.TextField(blank=True, default='OGEMED for you народився з простого бажання — зробити вибір косметики зрозумілим і спокійним.\n\nМи збираємо бренди, яким довіряємо самі, перевіряємо склади та умови зберігання, і супроводжуємо кожне замовлення від підбору до доставки в Україні.', verbose_name='Історія текст (UK)')),
                ('history_body_ru', models.TextField(blank=True, default='OGEMED for you родился из простого желания — сделать выбор косметики понятным и спокойным.\n\nМы собираем бренды, которым доверяем сами, проверяем составы и условия хранения, и сопровождаем каждый заказ от подбора до доставки в Украине.', verbose_name='Історія текст (RU)')),
                ('history_image', models.ImageField(blank=True, upload_to='about/', verbose_name='Історія зображення')),
                ('philosophy_visible', models.BooleanField(default=True, verbose_name='Філософія видима')),
                ('philosophy_kicker_uk', models.CharField(blank=True, default='Філософія догляду', max_length=80, verbose_name='Філософія kicker (UK)')),
                ('philosophy_kicker_ru', models.CharField(blank=True, default='Философия ухода', max_length=80, verbose_name='Філософія kicker (RU)')),
                ('philosophy_title_uk', models.CharField(blank=True, default='Менше шуму — більше уваги до шкіри', max_length=160, verbose_name='Філософія заголовок (UK)')),
                ('philosophy_title_ru', models.CharField(blank=True, default='Меньше шума — больше внимания к коже', max_length=160, verbose_name='Філософія заголовок (RU)')),
                ('philosophy_body_uk', models.TextField(blank=True, default='Ми віримо в догляд без зайвого тиску: чіткі рекомендації, чесні описи складів і засоби, які реально працюють у щоденній рутині.\n\nНаша мета — щоб ви відчували впевненість у виборі, а не втому від нескінченних обіцянок.', verbose_name='Філософія текст (UK)')),
                ('philosophy_body_ru', models.TextField(blank=True, default='Мы верим в уход без лишнего давления: чёткие рекомендации, честные описания составов и средства, которые реально работают в ежедневной рутине.\n\nНаша цель — чтобы вы чувствовали уверенность в выборе, а не усталость от бесконечных обещаний.', verbose_name='Філософія текст (RU)')),
                ('philosophy_image', models.ImageField(blank=True, upload_to='about/', verbose_name='Філософія зображення')),
                ('cta_visible', models.BooleanField(default=True, verbose_name='CTA видимий')),
                ('cta_title_uk', models.CharField(blank=True, default='Готові знайти свій догляд?', max_length=160, verbose_name='CTA заголовок (UK)')),
                ('cta_title_ru', models.CharField(blank=True, default='Готовы найти свой уход?', max_length=160, verbose_name='CTA заголовок (RU)')),
                ('cta_text_uk', models.TextField(blank=True, default='Перегляньте каталог або напишіть нам — підкажемо за брендом, типом шкіри чи доставкою.', verbose_name='CTA текст (UK)')),
                ('cta_text_ru', models.TextField(blank=True, default='Посмотрите каталог или напишите нам — подскажем по бренду, типу кожи или доставке.', verbose_name='CTA текст (RU)')),
                ('cta_catalog_label_uk', models.CharField(blank=True, default='До каталогу', max_length=80, verbose_name='CTA каталог (UK)')),
                ('cta_catalog_label_ru', models.CharField(blank=True, default='В каталог', max_length=80, verbose_name='CTA каталог (RU)')),
                ('cta_contacts_label_uk', models.CharField(blank=True, default='Контакти', max_length=80, verbose_name='CTA контакти (UK)')),
                ('cta_contacts_label_ru', models.CharField(blank=True, default='Контакты', max_length=80, verbose_name='CTA контакти (RU)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Про нас — контент',
                'verbose_name_plural': 'Про нас — контент',
            },
        ),
    ]
