# Generated by Django 5.2.16 on 2026-08-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_aboutcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_1_text_ru',
            field=models.TextField(blank=True, default='Чёткие рекомендации вместо громких обещаний — уход, который спокойно вписывается в ежедневную рутину.', verbose_name='Теза 1 — текст (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_1_text_uk',
            field=models.TextField(blank=True, default='Чіткі рекомендації замість гучних обіцянок — догляд, який спокійно вписується в щоденну рутину.', verbose_name='Теза 1 — текст (UK)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_1_title_ru',
            field=models.CharField(blank=True, default='Без лишнего давления', max_length=120, verbose_name='Теза 1 — заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_1_title_uk',
            field=models.CharField(blank=True, default='Без зайвого тиску', max_length=120, verbose_name='Теза 1 — заголовок (UK)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_2_text_ru',
            field=models.TextField(blank=True, default='Прозрачные описания средств и брендов, которым мы доверяем сами.', verbose_name='Теза 2 — текст (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_2_text_uk',
            field=models.TextField(blank=True, default='Прозорі описи засобів і брендів, яким ми довіряємо самі.', verbose_name='Теза 2 — текст (UK)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_2_title_ru',
            field=models.CharField(blank=True, default='Честные составы', max_length=120, verbose_name='Теза 2 — заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_2_title_uk',
            field=models.CharField(blank=True, default='Чесні склади', max_length=120, verbose_name='Теза 2 — заголовок (UK)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_3_text_ru',
            field=models.TextField(blank=True, default='Цель — чтобы вы чувствовали спокойствие в решении, а не усталость от бесконечного шума.', verbose_name='Теза 3 — текст (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_3_text_uk',
            field=models.TextField(blank=True, default='Мета — щоб ви відчували спокій у рішенні, а не втому від нескінченного шуму.', verbose_name='Теза 3 — текст (UK)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_3_title_ru',
            field=models.CharField(blank=True, default='Уверенный выбор', max_length=120, verbose_name='Теза 3 — заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_3_title_uk',
            field=models.CharField(blank=True, default='Впевнений вибір', max_length=120, verbose_name='Теза 3 — заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_body_ru',
            field=models.TextField(blank=True, default='Три принципа, из которых мы собираем каталог и сервис.', verbose_name='Філософія вступ (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_body_uk',
            field=models.TextField(blank=True, default='Три принципи, з яких ми збираємо каталог і сервіс.', verbose_name='Філософія вступ (UK)'),
        ),
    ]
