# Generated by Django 5.2.16 on 2026-08-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_about_philosophy_theses'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_4_text_ru',
            field=models.TextField(blank=True, default='Спокойствие в решении вместо усталости от бесконечного шума.', verbose_name='Теза 4 — текст (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_4_text_uk',
            field=models.TextField(blank=True, default='Спокій у рішенні замість втоми від нескінченного шуму.', verbose_name='Теза 4 — текст (UK)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_4_title_ru',
            field=models.CharField(blank=True, default='Уверенный выбор', max_length=120, verbose_name='Теза 4 — заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='philosophy_thesis_4_title_uk',
            field=models.CharField(blank=True, default='Впевнений вибір', max_length=120, verbose_name='Теза 4 — заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_1_text_ru',
            field=models.TextField(blank=True, default='Мягкий подход к коже без лишнего давления.', verbose_name='Теза 1 — текст (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_1_text_uk',
            field=models.TextField(blank=True, default='Мʼякий підхід до шкіри без зайвого тиску.', verbose_name='Теза 1 — текст (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_1_title_ru',
            field=models.CharField(blank=True, default='Забота', max_length=120, verbose_name='Теза 1 — заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_1_title_uk',
            field=models.CharField(blank=True, default='Турбота', max_length=120, verbose_name='Теза 1 — заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_2_text_ru',
            field=models.TextField(blank=True, default='Честные составы и бренды, которым мы доверяем сами.', verbose_name='Теза 2 — текст (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_2_text_uk',
            field=models.TextField(blank=True, default='Чесні склади й бренди, яким ми довіряємо самі.', verbose_name='Теза 2 — текст (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_2_title_ru',
            field=models.CharField(blank=True, default='Доверие', max_length=120, verbose_name='Теза 2 — заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_2_title_uk',
            field=models.CharField(blank=True, default='Довіра', max_length=120, verbose_name='Теза 2 — заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_3_text_ru',
            field=models.TextField(blank=True, default='Мера между эффективностью и мягкостью — без крайностей.', verbose_name='Теза 3 — текст (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_3_text_uk',
            field=models.TextField(blank=True, default='Міра між ефективністю й мʼякістю — без крайнощів.', verbose_name='Теза 3 — текст (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_3_title_ru',
            field=models.CharField(blank=True, default='Баланс', max_length=120, verbose_name='Теза 3 — заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_thesis_3_title_uk',
            field=models.CharField(blank=True, default='Баланс', max_length=120, verbose_name='Теза 3 — заголовок (UK)'),
        ),
    ]
