# Generated by Django 5.2.16 on 2026-08-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_about_philosophy_value_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_1_body_ru',
            field=models.TextField(blank=True, default='OGEMED for you родился из простого желания — сделать выбор косметики понятным и спокойным. Вместо хаоса обещаний мы хотели собрать пространство, где можно спокойно выбрать уход.\n\nСначала это были рекомендации друзьям и близким. Затем — каталог брендов, которым мы доверяем сами, и сервис с вниманием к деталям: от состава до условий хранения.', verbose_name='Картка 1 — текст (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_1_body_uk',
            field=models.TextField(blank=True, default='OGEMED for you народився з простого бажання — зробити вибір косметики зрозумілим і спокійним. Замість хаосу обіцянок ми хотіли зібрати простір, де можна спокійно обрати догляд.\n\nСпочатку це були рекомендації друзям і близьким. Згодом — каталог брендів, яким ми довіряємо самі, і сервіс з увагою до деталей: від складу до умов зберігання.', verbose_name='Картка 1 — текст (UK)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_1_title_ru',
            field=models.CharField(blank=True, default='Как появился OGEMED for you', max_length=160, verbose_name='Картка 1 — заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_1_title_uk',
            field=models.CharField(blank=True, default='Як зʼявився OGEMED for you', max_length=160, verbose_name='Картка 1 — заголовок (UK)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_2_body_ru',
            field=models.TextField(blank=True, default='Мы смотрим не только на «красивую банку». Важны состав, репутация производителя, логистика и то, как средство работает в ежедневной рутине — без лишнего шума и давления.\n\nКаждый бренд в каталоге проходит внутренний отбор: понятны ли описания, честны ли ожидания, удобно ли объяснить клиенту, зачем именно этот продукт.', verbose_name='Картка 2 — текст (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_2_body_uk',
            field=models.TextField(blank=True, default='Ми дивимось не лише на «красиву банку». Важливі склад, репутація виробника, логістика й те, як засіб працює в щоденній рутині — без зайвого шуму й тиску.\n\nКожен бренд у каталозі проходить внутрішній відбір: чи зрозумілі описи, чи чесні очікування, чи зручно пояснити клієнту, навіщо саме цей продукт.', verbose_name='Картка 2 — текст (UK)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_2_title_ru',
            field=models.CharField(blank=True, default='Что мы отбираем для каталога', max_length=160, verbose_name='Картка 2 — заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_2_title_uk',
            field=models.CharField(blank=True, default='Що ми відбираємо для каталогу', max_length=160, verbose_name='Картка 2 — заголовок (UK)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_3_body_ru',
            field=models.TextField(blank=True, default='Мы рядом на каждом шаге: поможем с подбором, подскажем по доставке Новой Почтой или курьером и ответим после получения, если что-то нужно уточнить.\n\nOGEMED for you — это не только витрина. Это забота о том, чтобы путь от выбора до вашей полки в Украине был спокойным, понятным и без лишних сюрпризов.', verbose_name='Картка 3 — текст (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_3_body_uk',
            field=models.TextField(blank=True, default='Ми поруч на кожному кроці: допоможемо з підбором, підкажемо щодо доставки Новою Поштою чи курʼєром і відповімо після отримання, якщо щось треба уточнити.\n\nOGEMED for you — це не лише вітрина. Це турбота про те, щоб шлях від вибору до вашої полиці в Україні був спокійним, зрозумілим і без зайвих сюрпризів.', verbose_name='Картка 3 — текст (UK)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_3_title_ru',
            field=models.CharField(blank=True, default='Как сопровождаем заказ', max_length=160, verbose_name='Картка 3 — заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='history_card_3_title_uk',
            field=models.CharField(blank=True, default='Як супроводжуємо замовлення', max_length=160, verbose_name='Картка 3 — заголовок (UK)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='history_body_ru',
            field=models.TextField(blank=True, default='', verbose_name='Історія текст (RU, запасний)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='history_body_uk',
            field=models.TextField(blank=True, default='', verbose_name='Історія текст (UK, запасний)'),
        ),
    ]
