# Generated by Django 5.2.16 on 2026-08-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_about_history_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('callback', 'Передзвоніть мені'), ('feedback', 'Зворотний звʼязок'), ('stock_notify', 'Повідомити про надходження')], default='callback', max_length=32),
        ),
    ]
