# Generated by Django 5.2.16 on 2026-08-24 12:37

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_lead_stock_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='hero_image',
            field=apps.core.fields.OptimizedImageField(blank=True, max_side=2560, upload_to='about/', verbose_name='Hero зображення'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='history_image',
            field=apps.core.fields.OptimizedImageField(blank=True, upload_to='about/', verbose_name='Історія зображення'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_image',
            field=apps.core.fields.OptimizedImageField(blank=True, upload_to='about/', verbose_name='Філософія зображення'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=apps.core.fields.OptimizedImageField(blank=True, max_side=2560, upload_to='hero/', verbose_name='Зображення'),
        ),
    ]
