# Generated by Django 5.2.16 on 2026-08-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_optimized_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('shipping', 'Доставка і оплата'), ('returns', 'Повернення'), ('privacy', 'Конфіденційність'), ('offer', 'Оферта')], max_length=32, unique=True, verbose_name='Сторінка')),
                ('cta_title_uk', models.CharField(blank=True, max_length=255, verbose_name='CTA заголовок (UK)')),
                ('cta_title_ru', models.CharField(blank=True, max_length=255, verbose_name='CTA заголовок (RU)')),
                ('cta_text_uk', models.TextField(blank=True, verbose_name='CTA текст (UK)')),
                ('cta_text_ru', models.TextField(blank=True, verbose_name='CTA текст (RU)')),
                ('note_title_uk', models.CharField(blank=True, max_length=255, verbose_name='Замітка — заголовок (UK)')),
                ('note_title_ru', models.CharField(blank=True, max_length=255, verbose_name='Замітка — заголовок (RU)')),
                ('note_steps_uk', models.TextField(blank=True, help_text='По одному кроку на рядок.', verbose_name='Кроки замітки (UK)')),
                ('note_steps_ru', models.TextField(blank=True, help_text='По одному кроку на рядок.', verbose_name='Кроки замітки (RU)')),
                ('note_text_uk', models.TextField(blank=True, verbose_name='Текст замітки (UK)')),
                ('note_text_ru', models.TextField(blank=True, verbose_name='Текст замітки (RU)')),
            ],
            options={
                'verbose_name': 'Мета інфо-сторінки',
                'verbose_name_plural': 'Мета інфо-сторінок',
            },
        ),
        migrations.CreateModel(
            name='InfoPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('shipping', 'Доставка і оплата'), ('returns', 'Повернення'), ('privacy', 'Конфіденційність'), ('offer', 'Оферта')], db_index=True, max_length=32, verbose_name='Сторінка')),
                ('layout', models.CharField(choices=[('card', 'Картка (заголовок / підзаголовок / текст)'), ('prose', 'Проза (заголовок / текст)')], default='card', max_length=16, verbose_name='Макет')),
                ('heading_uk', models.CharField(max_length=255, verbose_name='Заголовок (UK)')),
                ('heading_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (RU)')),
                ('subheading_uk', models.CharField(blank=True, help_text='Для макета «Картка» — рядок під заголовком.', max_length=255, verbose_name='Підзаголовок (UK)')),
                ('subheading_ru', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок (RU)')),
                ('body_uk', models.TextField(blank=True, verbose_name='Текст (UK)')),
                ('body_ru', models.TextField(blank=True, verbose_name='Текст (RU)')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Секція інфо-сторінки',
                'verbose_name_plural': 'Секції інфо-сторінок',
                'ordering': ['page_key', 'sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('callback', 'Передзвоніть мені'), ('feedback', 'Зворотний звʼязок'), ('stock_notify', 'Повідомити про надходження')], default='callback', max_length=32, verbose_name='Тип'),
        ),
    ]
