# Generated by Django 5.2.16 on 2026-08-24 13:58

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_cleanup_dead_cms_and_info_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='hero_image',
            field=apps.core.fields.OptimizedImageField(blank=True, help_text='Верхній банер «Про нас». Desktop ≈ 1920×800, WebP/JPEG.', max_side=2560, upload_to='about/', verbose_name='Зображення банера'),
        ),
    ]
