# Generated by Django 5.2.16 on 2026-08-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_admin_uk_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_catalog_label_ru',
            field=models.CharField(blank=True, default='В каталог', max_length=80, verbose_name='Кнопка «До каталогу» [RU]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_catalog_label_uk',
            field=models.CharField(blank=True, default='До каталогу', max_length=80, verbose_name='Кнопка «До каталогу» [UA]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_contacts_label_ru',
            field=models.CharField(blank=True, default='Контакты', max_length=80, verbose_name='Кнопка «Контакти» [RU]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_contacts_label_uk',
            field=models.CharField(blank=True, default='Контакти', max_length=80, verbose_name='Кнопка «Контакти» [UA]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_text_ru',
            field=models.TextField(blank=True, default='Посмотрите каталог или напишите нам — подскажем по бренду, типу кожи или доставке.', verbose_name='Текст нижнього блоку [RU]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_text_uk',
            field=models.TextField(blank=True, default='Перегляньте каталог або напишіть нам — підкажемо за брендом, типом шкіри чи доставкою.', verbose_name='Текст нижнього блоку [UA]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_title_ru',
            field=models.CharField(blank=True, default='Готовы найти свой уход?', max_length=160, verbose_name='Заголовок нижнього блоку [RU]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_title_uk',
            field=models.CharField(blank=True, default='Готові знайти свій догляд?', max_length=160, verbose_name='Заголовок нижнього блоку [UA]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_visible',
            field=models.BooleanField(default=True, verbose_name='Показувати нижній блок з кнопками'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='hero_kicker_ru',
            field=models.CharField(blank=True, default='OGEMED for you', max_length=80, verbose_name='Надпис над заголовком [RU]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='hero_kicker_uk',
            field=models.CharField(blank=True, default='OGEMED for you', max_length=80, verbose_name='Надпис над заголовком [UA]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='hero_text_ru',
            field=models.TextField(blank=True, default='Мы помогаем выбрать уход, которому можно доверять — спокойно, честно и с вниманием к вашей коже.', verbose_name='Текст банера [RU]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='hero_text_uk',
            field=models.TextField(blank=True, default='Ми допомагаємо обрати догляд, якому можна довіряти — спокійно, чесно і з увагою до вашої шкіри.', verbose_name='Текст банера [UA]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='hero_title_ru',
            field=models.CharField(blank=True, default='Красота с заботой о вас', max_length=160, verbose_name='Заголовок банера [RU]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='hero_title_uk',
            field=models.CharField(blank=True, default='Краса з турботою про вас', max_length=160, verbose_name='Заголовок банера [UA]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='hero_visible',
            field=models.BooleanField(default=True, verbose_name='Показувати верхній банер'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='history_kicker_ru',
            field=models.CharField(blank=True, default='История', max_length=80, verbose_name='Надпис секції «Історія» [RU]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='history_kicker_uk',
            field=models.CharField(blank=True, default='Історія', max_length=80, verbose_name='Надпис секції «Історія» [UA]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_kicker_ru',
            field=models.CharField(blank=True, default='Философия ухода', max_length=80, verbose_name='Надпис секції «Філософія» [RU]'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='philosophy_kicker_uk',
            field=models.CharField(blank=True, default='Філософія догляду', max_length=80, verbose_name='Надпис секції «Філософія» [UA]'),
        ),
    ]
