# Generated by Django 5.2.16 on 2026-09-29 07:59

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_about_human_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='cta_label_ru',
            field=models.CharField(blank=True, default='Смотреть', max_length=80, verbose_name='Текст кнопки (RU)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_label_uk',
            field=models.CharField(blank=True, default='Дивитись', max_length=80, verbose_name='Текст кнопки (UK)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_url',
            field=models.CharField(blank=True, default='/katalog/', max_length=255, verbose_name='Посилання кнопки'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=apps.core.fields.OptimizedImageField(blank=True, help_text='Банер: Desktop ≈1920×800; на мобільному обрізання по центру. Формат: JPG, PNG або WebP. Вага до 20 МБ (краще до 3 МБ).', max_side=2560, upload_to='hero/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='infopagemeta',
            name='cta_text_ru',
            field=models.TextField(blank=True, verbose_name='Текст форми (RU)'),
        ),
        migrations.AlterField(
            model_name='infopagemeta',
            name='cta_text_uk',
            field=models.TextField(blank=True, verbose_name='Текст форми (UK)'),
        ),
        migrations.AlterField(
            model_name='infopagemeta',
            name='cta_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок форми (RU)'),
        ),
        migrations.AlterField(
            model_name='infopagemeta',
            name='cta_title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок форми (UK)'),
        ),
    ]
